version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: qmtech
      POSTGRES_PASSWORD: qmtechpass
      POSTGRES_DB: qmtechdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.11-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:
