spring:
  application:
    name: qmtech-scheduled-live
  datasource:
    url: jdbc:postgresql://localhost:5432/qmtechdb
    username: qmtech
    password: qmtechpass
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

server:
  port: 8080